### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [kkashyn/grid-template-init-project#1]
картинка повторилась )
![image](https://user-images.githubusercontent.com/8464662/77102191-1a8af200-6a21-11ea-99bb-bfe12e44e297.png)

нет соответствия макету:

1)
цвет плэйсхолдера
![image](https://user-images.githubusercontent.com/8464662/77102222-2aa2d180-6a21-11ea-9dff-b8fccff64758.png)

**Comment by kkashyn** [comment]
done
